apiVersion: v1
kind: Namespace
metadata:
  name: ocr-app
  labels:
    managed-by: portainer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-config
  namespace: ocr-app
data:
  OCR_API_KEY: "your_api_key_here"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-pvc
  namespace: ocr-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
  namespace: ocr-app
  labels:
    app: ocr
    managed-by: portainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
        - name: ocr-container
          image: myrepo/ocr-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ocr-config
          volumeMounts:
            - mountPath: "/app/data"
              name: ocr-storage
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: ocr-storage
          persistentVolumeClaim:
            claimName: ocr-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
  namespace: ocr-app
  labels:
    managed-by: portainer
spec:
  selector:
    app: ocr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
